# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigGod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('description', models.TextField()),
                ('github', models.URLField()),
            ],
        ),
    ]
