# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_biggod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biggod',
            name='image',
            field=models.ImageField(upload_to='persons'),
        ),
    ]
