# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20161219_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='biggod',
            name='english_name',
            field=models.CharField(default='lurenjia', max_length=10),
        ),
        migrations.AlterField(
            model_name='biggod',
            name='name',
            field=models.CharField(default='\u8def\u4eba\u7532', max_length=10),
        ),
    ]
