# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20161220_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='biggod',
            name='description',
        ),
        migrations.AddField(
            model_name='biggod',
            name='description',
            field=models.ManyToManyField(to='portal.Tag'),
        ),
    ]
