# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20161220_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biggod',
            name='github',
        ),
    ]
